server:
  port: 9006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teachers
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  application:
    name: teacher-service

  jpa:
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.youdomjames.teacher_service: DEBUG
    web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/