spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  #Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    com.youdomjames.course_service: DEBUG
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info