server:
  port: 9000
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: courses_route
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**
        - id: teachers_route
          uri: lb://teacher-service
          predicates:
            - Path=/api/v1/teachers/**
        - id: students_route
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  title: API Gateway
  version: v1.0.0
