server:
  port: 9007

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3307/students
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.youdomjames.teacher_service: DEBUG
    web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/