server:
  port: 9007

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/students
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.youdomjames.teacher_service: DEBUG
    web: DEBUG