server:
  port: 0

spring:
  datasource:
    url: ${MYSQL_STUDENTS_DB_URL}
    username: ${MYSQL_STUDENTS_DB_USERNAME}
    password: ${MYSQL_STUDENTS_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_URL}

logging:
  level:
    com.youdomjames.course_service: INFO
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info